// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiLineCharOutput;

namespace MultiLineCharOutput.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MultiLineCharOutput.AP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountType");

                    b.Property<string>("Bank");

                    b.Property<string>("BankAcctNbr");

                    b.Property<string>("BankAcctTransit");

                    b.Property<decimal>("CheckAmt");

                    b.Property<string>("CheckDate");

                    b.Property<string>("CheckNumber");

                    b.Property<string>("CompanyCode");

                    b.Property<decimal>("DiscountAmt");

                    b.Property<string>("EffectiveDate");

                    b.Property<string>("EftAdviceNum");

                    b.Property<decimal>("EftAmt");

                    b.Property<string>("EftTraceNum");

                    b.Property<string>("EntryDate");

                    b.Property<string>("GenericName2");

                    b.Property<decimal>("InvoiceAmt");

                    b.Property<string>("InvoiceDate");

                    b.Property<decimal>("NetInvoiceAmt");

                    b.Property<string>("PayDate");

                    b.Property<string>("PaymentId");

                    b.Property<string>("PaymentMode");

                    b.Property<string>("RcrsAccountNum");

                    b.Property<string>("RcrsTransitRoute");

                    b.Property<string>("RecvPartAcctType");

                    b.Property<string>("ReferenceData");

                    b.Property<string>("RemitAddress1");

                    b.Property<string>("RemitAddress2");

                    b.Property<string>("RemitAddress3");

                    b.Property<string>("RemitCity");

                    b.Property<string>("RemitCountryCode");

                    b.Property<string>("RemitState");

                    b.Property<string>("RemitZipcode");

                    b.Property<string>("SourceCode");

                    b.Property<string>("StatusInd");

                    b.Property<string>("TinType");

                    b.Property<string>("TranHdrDesc");

                    b.Property<string>("VendorId");

                    b.Property<string>("VendorName1");

                    b.HasKey("Id");

                    b.ToTable("APs");
                });
#pragma warning restore 612, 618
        }
    }
}
